### ISSUE TITLE
Better way to automatically unbind device?

### ISSUE THREAD

**Issue by compiaffe** [Roboy/flexrayusbinterface#13]
We have another working udev rule from one of our partners:

```
SUBSYSTEMS=="usb", ATTR{idVendor}=="0403", ATTR{idProduct}=="6014", ATTR{serial}=="FTY4PDYV", RUN+="/bin/sh -c 'echo -n %k >/sys%p/driver/unbind'"
```

You could leave away the `ATTR{serial}=="FTY4PDYV"` if you want to match every FTDI UM232H device.

Currently implemented is the following udev rule:

```
ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6014", MODE:="0666"
ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6014", RUN+="/bin/sh -c 'echo $kernel > /sys/bus/usb/drivers/ftdi_sio/unbind'"
```

----
Any preferences? @victor-savu

**Comment by Victor-Savu** [comment]
This is at the very edge of the library, so I guess anything goes (including running in `sudo`). I really have no preference -- whatever works.
